syntax = "proto3";

package onchain;

service onChainSerivce {
    rpc Deposit(DepositRequest) returns (DepositResponse);
    rpc Withdraw(WithdrawRequest) returns (WithdrawResponse);
    rpc Sell(SellRequest) returns (SellResponse);
    rpc Buy(BuyRequest) returns (BuyResponse);
}

message DepositRequest {
    string chain = 1; // solana = 1, ethereum = 2, binance = 3
    string amount = 2; // Deposit amount
}

message DepositResponse {
    bool success = 1;
    string message = 2;
    string hot_wallet_balance = 3;
}

message WithdrawRequest {}

message WithdrawResponse {}

message SellRequest {}

message SellResponse {}

message BuyRequest {}

message BuyResponse {}